### ISSUE TITLE
challenge bot should not report error when the challenge program is not reward

### ISSUE THREAD

**Issue by zhouqiang-cl** [tidb-community-bots/ti-challenge-bot#150]
## Bug Report

- [x] I have searched the [issues](https://github.com/tidb-community-bots/challenge-bot/issues) of this repository and believe that this is not a duplicate.

### Related link

- Which project: TiDB

- PR or Issue Link: https://github.com/pingcap/tidb/pull/20288
### What is expected?

challenge bot should not report error when the challenge program is not reward

### What is actually happening?

<img width="865" alt="截屏2020-09-29 下午5 03 23" src="https://user-images.githubusercontent.com/23521459/94537770-c4bbc000-0275-11eb-9f7f-38f8ea338efb.png">

Now it reports an error and makes us confused

**Comment by Rustin-Liu** [comment]
The CI status should be `pending`.
