### ISSUE TITLE
Enhanced command limit

### ISSUE THREAD

**Issue by hi-rustin** [tidb-community-bots/ti-challenge-bot#52]
## Bug Report

- [x] I have searched the [issues](https://github.com/tidb-community-bots/challenge-bot/issues) of this repository and believe that this is not a duplicate.

### Related link

None

### Steps to reproduce(Optional)

Reward on Issue.
Pick up on PR.

### What is expected?
No reaction.

### What is actually happening?
Bot commented.

**Comment by Mini256** [comment]
In the probot version 9, `the context.issue()` return the `number` of issue or pull request.We can distinguish them by the `pull_request` attribute of the response.

Response of the issue obtained through `context.github.issues.get()` API:

![Snipaste_2020-11-24_11-10-50](https://user-images.githubusercontent.com/5086433/100042300-2481b200-2e46-11eb-9829-f660a88223e1.png)

Response of the pull request obtained through `context.github.pulls.get()` API:

![Snipaste_2020-11-24_11-11-09-2](https://user-images.githubusercontent.com/5086433/100042333-32cfce00-2e46-11eb-99c8-c680213721a3.png)

But after the version [10.0.0-beta.9](https://github.com/probot/probot/compare/v10.0.0-beta.8...v10.0.0-beta.9)，Probot provide the `context.issue()` and the `context.pullRequest()` API to distinguish them.
